// <auto-generated />
using System;
using ManagerStudent.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManagerStudent.Infrastructure.Migrations
{
    [DbContext(typeof(ManagerStundetContext))]
    partial class ManagerStundetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ManagerStudent.Core.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = 73,
                            Date = new DateTime(2022, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 74,
                            Date = new DateTime(2022, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 75,
                            Date = new DateTime(2022, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "E",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 77,
                            Date = new DateTime(2022, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 78,
                            Date = new DateTime(2022, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 7
                        },
                        new
                        {
                            Id = 79,
                            Date = new DateTime(2022, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 8
                        },
                        new
                        {
                            Id = 80,
                            Date = new DateTime(2022, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 9
                        },
                        new
                        {
                            Id = 81,
                            Date = new DateTime(2022, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 10
                        },
                        new
                        {
                            Id = 82,
                            Date = new DateTime(2022, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 16
                        },
                        new
                        {
                            Id = 83,
                            Date = new DateTime(2022, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 17
                        },
                        new
                        {
                            Id = 84,
                            Date = new DateTime(2022, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 18
                        },
                        new
                        {
                            Id = 85,
                            Date = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 86,
                            Date = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 87,
                            Date = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 89,
                            Date = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 90,
                            Date = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 7
                        },
                        new
                        {
                            Id = 91,
                            Date = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 8
                        },
                        new
                        {
                            Id = 92,
                            Date = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 9
                        },
                        new
                        {
                            Id = 93,
                            Date = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 10
                        },
                        new
                        {
                            Id = 94,
                            Date = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 16
                        },
                        new
                        {
                            Id = 95,
                            Date = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 17
                        },
                        new
                        {
                            Id = 96,
                            Date = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 18
                        },
                        new
                        {
                            Id = 109,
                            Date = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 110,
                            Date = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 111,
                            Date = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "E",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 113,
                            Date = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "E",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 114,
                            Date = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "E",
                            StudentId = 7
                        },
                        new
                        {
                            Id = 115,
                            Date = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 8
                        },
                        new
                        {
                            Id = 116,
                            Date = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 9
                        },
                        new
                        {
                            Id = 117,
                            Date = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 10
                        },
                        new
                        {
                            Id = 118,
                            Date = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 16
                        },
                        new
                        {
                            Id = 119,
                            Date = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 17
                        },
                        new
                        {
                            Id = 120,
                            Date = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 18
                        },
                        new
                        {
                            Id = 121,
                            Date = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 122,
                            Date = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 123,
                            Date = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 125,
                            Date = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 126,
                            Date = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 7
                        },
                        new
                        {
                            Id = 127,
                            Date = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 8
                        },
                        new
                        {
                            Id = 128,
                            Date = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 9
                        },
                        new
                        {
                            Id = 129,
                            Date = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 10
                        },
                        new
                        {
                            Id = 130,
                            Date = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 16
                        },
                        new
                        {
                            Id = 131,
                            Date = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 17
                        },
                        new
                        {
                            Id = 132,
                            Date = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 18
                        },
                        new
                        {
                            Id = 133,
                            Date = new DateTime(2022, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 134,
                            Date = new DateTime(2022, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 135,
                            Date = new DateTime(2022, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 137,
                            Date = new DateTime(2022, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 138,
                            Date = new DateTime(2022, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 7
                        },
                        new
                        {
                            Id = 139,
                            Date = new DateTime(2022, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 8
                        },
                        new
                        {
                            Id = 140,
                            Date = new DateTime(2022, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 9
                        },
                        new
                        {
                            Id = 141,
                            Date = new DateTime(2022, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 10
                        },
                        new
                        {
                            Id = 142,
                            Date = new DateTime(2022, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 16
                        },
                        new
                        {
                            Id = 143,
                            Date = new DateTime(2022, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 17
                        },
                        new
                        {
                            Id = 144,
                            Date = new DateTime(2022, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 18
                        },
                        new
                        {
                            Id = 167,
                            Date = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "E",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 168,
                            Date = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "E",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 169,
                            Date = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 170,
                            Date = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 171,
                            Date = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 7
                        },
                        new
                        {
                            Id = 172,
                            Date = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 8
                        },
                        new
                        {
                            Id = 173,
                            Date = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "E",
                            StudentId = 9
                        },
                        new
                        {
                            Id = 174,
                            Date = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 10
                        },
                        new
                        {
                            Id = 175,
                            Date = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "E",
                            StudentId = 16
                        },
                        new
                        {
                            Id = 176,
                            Date = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "A",
                            StudentId = 17
                        },
                        new
                        {
                            Id = 177,
                            Date = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "P",
                            StudentId = 18
                        });
                });

            modelBuilder.Entity("ManagerStudent.Core.Entities.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<byte>("Value")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Scores");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            StudentId = 2,
                            SubjectId = 1,
                            Value = (byte)70
                        },
                        new
                        {
                            Id = 3,
                            StudentId = 3,
                            SubjectId = 1,
                            Value = (byte)80
                        },
                        new
                        {
                            Id = 4,
                            StudentId = 4,
                            SubjectId = 1,
                            Value = (byte)78
                        },
                        new
                        {
                            Id = 6,
                            StudentId = 6,
                            SubjectId = 1,
                            Value = (byte)98
                        },
                        new
                        {
                            Id = 7,
                            StudentId = 7,
                            SubjectId = 1,
                            Value = (byte)67
                        },
                        new
                        {
                            Id = 8,
                            StudentId = 8,
                            SubjectId = 1,
                            Value = (byte)89
                        },
                        new
                        {
                            Id = 9,
                            StudentId = 9,
                            SubjectId = 1,
                            Value = (byte)78
                        },
                        new
                        {
                            Id = 10,
                            StudentId = 10,
                            SubjectId = 1,
                            Value = (byte)97
                        },
                        new
                        {
                            Id = 11,
                            StudentId = 16,
                            SubjectId = 1,
                            Value = (byte)98
                        },
                        new
                        {
                            Id = 12,
                            StudentId = 17,
                            SubjectId = 1,
                            Value = (byte)87
                        },
                        new
                        {
                            Id = 16,
                            StudentId = 2,
                            SubjectId = 2,
                            Value = (byte)87
                        },
                        new
                        {
                            Id = 17,
                            StudentId = 3,
                            SubjectId = 2,
                            Value = (byte)67
                        },
                        new
                        {
                            Id = 18,
                            StudentId = 4,
                            SubjectId = 2,
                            Value = (byte)87
                        },
                        new
                        {
                            Id = 20,
                            StudentId = 6,
                            SubjectId = 2,
                            Value = (byte)86
                        },
                        new
                        {
                            Id = 21,
                            StudentId = 8,
                            SubjectId = 2,
                            Value = (byte)86
                        });
                });

            modelBuilder.Entity("ManagerStudent.Core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Comment = "Buen estudiante",
                            LastName = "Velazquez",
                            Name = "Alfredo"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Buen estudiante",
                            LastName = "Flores",
                            Name = "Maria"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Mal estudiante",
                            LastName = "Lorenzo",
                            Name = "Ramon"
                        },
                        new
                        {
                            Id = 6,
                            Comment = "muy Buen estudiante",
                            LastName = "Castillo",
                            Name = "Isamal"
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Buen estudiante",
                            LastName = "Monte",
                            Name = "Fernado"
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Buen estudiante",
                            LastName = "Puentes",
                            Name = "Samuel"
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Mal estudiante",
                            LastName = "Perez",
                            Name = "Ana"
                        },
                        new
                        {
                            Id = 10,
                            Comment = "buen estudiante",
                            LastName = "Martinez",
                            Name = "Liz"
                        },
                        new
                        {
                            Id = 16,
                            Comment = "take attendancetake attendancetake attendancetake attendancetake attendancetake attendance",
                            LastName = "Santos",
                            Name = "Fany"
                        },
                        new
                        {
                            Id = 17,
                            Comment = "",
                            LastName = "Manuel",
                            Name = "Junior"
                        },
                        new
                        {
                            Id = 18,
                            Comment = "",
                            LastName = "Carmona",
                            Name = "Gabriel"
                        },
                        new
                        {
                            Id = 19,
                            Comment = "Buen estudiante",
                            LastName = "test",
                            Name = "Update student"
                        });
                });

            modelBuilder.Entity("ManagerStudent.Core.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Matematicas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lengua española"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ciencias Sociales"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ciencias Naturales"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fisica"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Artistica"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Moral y Civica"
                        });
                });

            modelBuilder.Entity("ManagerStudent.Core.Entities.Attendance", b =>
                {
                    b.HasOne("ManagerStudent.Core.Entities.Student", null)
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManagerStudent.Core.Entities.Score", b =>
                {
                    b.HasOne("ManagerStudent.Core.Entities.Student", null)
                        .WithMany("Scores")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagerStudent.Core.Entities.Subject", null)
                        .WithMany("Scores")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManagerStudent.Core.Entities.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("ManagerStudent.Core.Entities.Subject", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
